// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 d7r LLC

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')

const TARGETS = [
  { contract: 'SAGAHandleRegistry', exportName: 'SAGAHandleRegistryAbi' },
  { contract: 'SAGAAgentIdentity', exportName: 'SAGAAgentIdentityAbi' },
  { contract: 'SAGAOrgIdentity', exportName: 'SAGAOrgIdentityAbi' },
  { contract: 'SAGADirectoryIdentity', exportName: 'SAGADirectoryIdentityAbi' },
  // Phase 10 (M-8): the README lists SAGATBAHelper as a package contract;
  // export the ABI so frontends/indexers can call computeAccount /
  // computeAccountForChain / createAccount via the deployed helper
  // instead of reimplementing ERC-6551 derivation off-chain (which
  // drifts from the helper's immutable registry/implementation refs).
  { contract: 'SAGATBAHelper', exportName: 'SAGATBAHelperAbi' },
]

const HEADER = `// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 d7r LLC
//
// Auto-generated by scripts/generate-abis.mjs from out/<Contract>.sol/<Contract>.json.
// Do not edit by hand. Re-run \`node scripts/generate-abis.mjs\` after changes.
`

for (const { contract, exportName } of TARGETS) {
  const artifactPath = resolve(ROOT, 'out', `${contract}.sol`, `${contract}.json`)
  const artifact = JSON.parse(readFileSync(artifactPath, 'utf8'))
  const abi = artifact.abi
  const body = `${HEADER}\nexport const ${exportName} = ${JSON.stringify(abi, null, 2)} as const\n`
  const outPath = resolve(ROOT, 'src', 'ts', 'abis', `${contract}.ts`)
  writeFileSync(outPath, body)
  // eslint-disable-next-line no-console
  console.log(`wrote ${outPath} (${abi.length} entries)`)
}
