// Copyright 2026 d7r LLC
// SPDX-License-Identifier: Apache-2.0

import { type SearchOptions } from 'flexsearch'

declare module '@/markdoc/search.mjs' {
  export type Result = {
    url: string
    title: string
    pageTitle?: string
  }

  export function search(query: string, options?: SearchOptions): Array<Result>
}

/**
 * CloudflareEnv augmentation. The base type is generated by
 * @opennextjs/cloudflare from wrangler.jsonc; we extend it here for
 * bindings that aren't picked up automatically (e.g. service
 * bindings, which OpenNext doesn't surface in its generated types
 * yet).
 */
declare global {
  interface CloudflareEnv {
    /**
     * Service binding to the saga-server worker on the same Cloudflare
     * account. Bypasses the public *.workers.dev hostname (which 1042s
     * on same-account loopback fetches) by routing the call directly
     * via Cloudflare's internal RPC. See wrangler.jsonc env.staging.services.
     *
     * Only present in environments where wrangler.jsonc declares a
     * `services` block — undefined in dev/local. Use a runtime guard
     * before relying on it.
     */
    SAGA_SERVER?: Fetcher
  }
}

export {}
